[workspace]
authors = ["NapatzZ <Napat559977@outlook.co.th>"]
channels = ["conda-forge", "robostack-humble"]
name = "yahboom_abu_ws"
platforms = ["osx-arm64"]
version = "0.1.0"

[activation]
env = { RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp", LDFLAGS = "-L$PIXI_PROJECT_ROOT/.pixi/envs/default/lib", LIBRARY_PATH = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib", DYLD_LIBRARY_PATH = "$PIXI_PROJECT_ROOT/install/lib:$PIXI_PROJECT_ROOT/.pixi/envs/default/lib", ROS_DOMAIN_ID = "20", AMENT_PREFIX_PATH = "$PIXI_PROJECT_ROOT/install:$PIXI_PROJECT_ROOT/.pixi/envs/default" }

[tasks]
build = "colcon build --symlink-install --merge-install"
bringup = "ros2 launch yahboom_bringup native_bringup.launch.py"
navigate = "ros2 launch yahboom_nav2 navigate.launch.py"
rf2o = "ros2 launch yahboom_bringup rf2o.launch.py"
agent-udp = "docker run -it --rm -p 8090:8090/udp microros/micro-ros-agent:humble udp4 --port 8090 -v4"
agent-serial = "docker run -it --rm --privileged -v /dev:/dev microros/micro-ros-agent:humble serial --dev /dev/ttyUSB0 -b 921600 -v4"
rviz = "rviz2"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-nav2-msgs = ">=1.1.20,<2"
ros-humble-nav2-bringup = ">=1.1.20,<2"
ros-humble-tf-transformations = ">=1.1.1,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-humble-rmw-cyclonedds-cpp = ">=1.3.4,<2"
ros-humble-odom-to-tf-ros2 = ">=1.0.7,<2"
ros-humble-robot-localization = ">=3.5.4,<4"
ros-humble-slam-toolbox = ">=2.6.10,<3"
pyserial = ">=3.5,<4"
ros-humble-joint-state-publisher = ">=2.4.0,<3"
ros-humble-xacro = ">=2.1.1,<3"
